export enum ProjectType {
  COMMERCIAL = 'COMMERCIAL',
  MAINTENANCE = 'MAINTENANCE',
  PRODUCTION = 'PRODUCTION',
  SERVICES = 'SERVICES',
  CONSTRUCTION = 'CONSTRUCTION',
  TECHNOLOGY = 'TECHNOLOGY',
}
